### PR TITLE
!! Removing inappropriate content

### PR DESCRIPTION
**Pull request by Seneral**
In other words, censor that key (in all forks, too). No API key should be public.

Sorry for the messy commits. Made a quick and dirty change over the browser.

### CODE REVIEW

**Comment by NatoBoram** [comment]
We might need to ask @pcouy if this was a decoy or an Inspect Element edit!

**Comment by pcouy** [comment]
I meant to delete the key after taking the screenshots but then I forgot about it. Good thing you noticed it, but now the key has been deleted so I won't merge the pull request. Thank you anyway

**Comment by Seneral** [comment]
Alright, that's even better then:)

**Comment by pcouy** [comment]
Yes. Since it is possible to retrieve file versions from previous commits, it would have been useless to just replace the picture

**Pull request closed without merging**
