### PR TITLE
Fixed playlists video titles not updating

### PR DESCRIPTION
**Pull request by Seneral**
Modified the radio and mix fix again, this time with proper include and exclude list as to not make an error again. Result is even neater than before.

### CODE REVIEW

**Comment by Seneral** [comment]
Another small reminder for a merge, a few more fixes have been added (not including the issues still present on this github, but other, more hidden errors)

**Comment by Seneral** [comment]
Added support for timestamp links in video description (#15)
It is not perfect, for some reason clicking my linkified timestamps reloads the whole window, whereas with youtube's default timestamps it does not, despite being exactly the same HTML code.
There's probably some magic going on when youtube enters prepares the text (like setting these links on a watchlist, nothing that could be traced back the the HTML code...).
Also, I did NOT yet test timestamps including hours (1:11:11), but it should work just fine.

**Comment by Seneral** [comment]
Any plans to accept and update? It's not a trivial update anymore with several fixes so it'd rather have it updated officially.

**Comment by pcouy** [comment]
Thank you for being invested in this project. The improvements you made look neat, but since I was satisfied with the (somewhat incomplete and buggy) previous version, I did not take the time to try it out. Please accept my apologies for not giving enough consideration to your hard work.

I will have some free time soon and will gladly merge this after I try it out and review the code. Do you still use it ? Does it still work smoothly ?

**Comment by Seneral** [comment]
Ya it's fine, can understand.
Seems so, although over the months I had one or two cases where the titles were mismatched. Considering how often I use YT this is a very low failure rate but can't claim it's 100% stable. Changes I made are definitely fixing the stuff they're supposed to fix, that I can assure.

Edit: Well, the livestream description duplication bug is still there, but it hasn't bothered me too much so far.

**Pull request merged**
