### PR TITLE
Cancel translation without API

### PR DESCRIPTION
**Pull request by ftoh**
I spent time exploring YouTube's code, and I found a solution how to cancel translation without an API.

Difference:
 - [x] Not required API, works without http requests
 - [x] Not uses local storage
 - [x] Not uses timers, only event handling
 - [x] Pretty console output
 - [x] Linkify Unicode urls
 - [x] Linkify Unicode hashtags
 - [x] Linkify timecodes
 - [ ] Linkify emails
 - [ ] Linkify links without protocol
 - [ ] Linkify ftp links
 - [ ] Checked only on Chrome-based browser

Sample of console output:
image

### CODE REVIEW

**Comment by Seneral** [comment]
Very interesting, but your branch is private which makes it hard to test out. 
Here's the raw link: https://github.com/pcouy/YoutubeAutotranslateCanceler/raw/edd4c5d508ce07135e9b4bb42026a3b3f44a729a/AntiTranslate.user.js

**Comment by Seneral** [comment]
Ok am a bit stumped right now. Looking at the code it looked like it only works on the watch page, went to verify it by going on playlists, channels, front page. And for some reason, with no scripts installed, the channel page (for example) displays the original title now even though it displays as a different language when clicking on the video.
This seems to be new , doesn't it? I know for sure we had to put some effort in for all of these pages to be reverted properly...

In any case, if this is permanent, then I see no reason to not accept the script.
It's way more elegant and can't imagine how much effort it took to reverse engineer the mess they call polymer. Will report back if I find any issues. Thanks!

Btw, not sure if @pcouy is still active. Waited a few months now to get my PR accepted which fixed alot of bugs, but no response.

**Comment by ftoh** [comment]
> This seems to be new , doesn't it? 

Yeah, I noticed it about a month ago.

**Comment by Seneral** [comment]
Just tested it on linux and got some errors. On Windows it worked really well over the past two weeks.
Here's what I changed to make it work (I'll just dump this here since it probably won't work on Windows anymore. Will check later how to best handle this):
Line 40:
```
//var vedeoData = window['page-manager'].__data__.data
var vedeoData = window['page-manager'].__data.data
```
Line 60:
```
//var plainDescription = secn.description.runs.map(i => i.text).join('')
var plainDescription = secn.description.simpleText
```

**Comment by ftoh** [comment]
> var plainDescription = secn.description.simpleText

It's different on different videos

```
window['page-manager'].__data.data.response.contents.twoColumnWatchNextResults.results.results.contents[1].videoSecondaryInfoRenderer.description
```
https://www.youtube.com/watch?v=YMozhzt6s70 - simpleText
https://www.youtube.com/watch?v=astISOttCQ0 - runs

it should work
```
var plainDescription = secn.description.simpleText || secn.description.runs.map(i => i.text).join('')
```

**Comment by Seneral** [comment]
Hm interesting, thanks:)
Same with the data though?

**Comment by ftoh** [comment]
No. Just YouTube changed code

**Comment by Seneral** [comment]
Seems like YouTube resumed translating the titles in other pages:( Unless this somehow can be adapted to work on other videos (which I highly doubt), i'd be back again to the old solution...

**Comment by ftoh** [comment]
I checked the code. YouTube does not keep original titles

**Comment by pcouy** [comment]
Hi !
Thank you @FTOH for your work. This is the kind of thing I was going for when I wrote this script, before I realized how difficult it would be, and how the slightest changes to YouTube's code would break it. That is why I chose to go the _hacky_ way.

I do not have time to check it out in details, but while it looks like some hard work, the fact that you rewrote almost everything and that you deeply changed how it works under the hood makes be believe your code belongs in its own repo. I can link to your repo in my readme if you want to.

**Pull request closed without merging**
